name: Download the leaves
on:
    workflow_dispatch:
permissions:
    actions: write
    id-token: write
    contents: write
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
            - name: Download the leaves
              continue-on-error: true
              run: |
                    pip install -r requirements.txt
                    python try3.py
            - name: Commit the changes
              continue-on-error: true
              run: |
                    git pull origin main 
                    git config --global user.name "GitHub Actions"
                    git config --global user.email "shantanu561993@gmail.com"
                    git add --all
                    git commit -m "Download the leaves"
                    git push -f origin main

